// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKqk7fqfUID9nHm4FpoymK0JI0Qni8KeY',
    appId: '1:925555659968:web:9423afac19d1cf68ea4925',
    messagingSenderId: '925555659968',
    projectId: 'chat-me-dc32d',
    authDomain: 'chat-me-dc32d.firebaseapp.com',
    storageBucket: 'chat-me-dc32d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYFsfI8gi9lfdt4vNjCYIc7a4YEAsbJHk',
    appId: '1:925555659968:android:d6e05546813aa498ea4925',
    messagingSenderId: '925555659968',
    projectId: 'chat-me-dc32d',
    storageBucket: 'chat-me-dc32d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lQt4yD682lRa9k6frbtYZ3Atgq3oF40',
    appId: '1:925555659968:ios:4d2826725b9d8430ea4925',
    messagingSenderId: '925555659968',
    projectId: 'chat-me-dc32d',
    storageBucket: 'chat-me-dc32d.appspot.com',
    iosClientId: '925555659968-ok0359b0vkg3g5ed6ge74mbrj4evgd5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5lQt4yD682lRa9k6frbtYZ3Atgq3oF40',
    appId: '1:925555659968:ios:4d2826725b9d8430ea4925',
    messagingSenderId: '925555659968',
    projectId: 'chat-me-dc32d',
    storageBucket: 'chat-me-dc32d.appspot.com',
    iosClientId: '925555659968-ok0359b0vkg3g5ed6ge74mbrj4evgd5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatMe',
  );
}
